[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[variables]
VITE_API_URL = "http://localhost:5000/api"

[start]
cmd = "npx http-server dist -p 3000 --proxy http://localhost:3000? -c-1"
