[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "node prisma/seed.js; node --max-http-header-size=32768 src/server.js"
