[phases.setup]
nixPkgs = ["openssl", "nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && npm ci --omit=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate",
  "cp -r frontend/dist backend/frontend-dist"
]

[start]
cmd = "cd backend && node prisma/seed.js; node --max-http-header-size=32768 src/server.js"
